repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        files: ^(src|tests)/.*\.py$
        pass_filenames: false
        args: [src, tests]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check
        language: system
        files: ^(src|tests)/.*\.py$
        pass_filenames: false
        args: [src, tests]
      #  - id: mypy
      #    name: mypy
      #    entry: uv run mypy
      #    language: system
      #    files: ^src/.*\.py$
      #    pass_filenames: false
      #    args: [src]
      #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: debug-statements
